add lecture 5 homework:
ozoncp/ocp-vacancy-api pull request #5
Opened 2021-08-09 13:45 UTC by bukhtiyarovanton

- saver interface with mocks and tests

2021-08-10 08:43 UTC, ivanmakarychev requested changes

2021-08-10 08:43 UTC, ivanmakarychev commented on internal/saver/saver.go
> +	doneCh  chan bool
Для таких целей можно использовать chan struct{}. Пустая структура не требует никакого места в памяти. В данном случае, конечно, оптимизация несущественная.

2021-08-10 08:43 UTC, ivanmakarychev commented on internal/saver/saver.go
> +		// TODO: Unclear what to de here
В задании не указано, что делать. Вакансии могли не сохраниться из-за того, что база была недоступна - тогда разумно попробовать повторить, т.е. добавить вакансии обратно в s.storage. Если они не сохранились из-за ограничений в базе, то повторять нет смысла. Скорее всего, мы рассчитываем, что мы правильно валидируем входные данные и не могли вставить вакансии, которые не соответствуют ограничениям в базе, поэтому, видимо, нужно добавить вакансии обратно в s.storage.

2021-08-16 15:30 UTC, bukhtiyarovanton commented on internal/saver/saver.go
> +	doneCh  chan bool
fixed

2021-08-16 15:30 UTC, bukhtiyarovanton commented on internal/saver/saver.go
> +		// TODO: Unclear what to de here
fixed

2021-08-17 05:47 UTC, ivanmakarychev approved these changes

2021-08-17 14:40 UTC, merged