Feature/lecture 6 homework
ozoncp/ocp-vacancy-api pull request #6
Opened 2021-08-17 02:52 UTC by bukhtiyarovanton

lecture 6 homework:
- add gRPC service to handle vacancies
- add Makefile to build binary, generate gRPC server and client
-  add Dockerfile to build an image

2021-08-18 07:16 UTC, ivanmakarychev requested changes

2021-08-18 07:16 UTC, ivanmakarychev commented on Dockerfile
> +EXPOSE 8081 8082
нужно исправить порт 8082 на 8083

2021-08-18 07:31 UTC, ivanmakarychev requested changes

2021-08-18 07:31 UTC, ivanmakarychev commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +    uint64 ID = 1;
По конвенции поля должны быть в snake_case
https://developers.google.com/protocol-buffers/docs/style?hl=ru

2021-08-18 07:31 UTC, ivanmakarychev commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +    uint64 Status = 2 [(validate.rules).uint64.gte = 0];
Здорово, что добавил валидацию, хотя в случае с uint64 проверка на >= 0 не имеет особого смысла

2021-08-18 07:31 UTC, ivanmakarychev commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +syntax = "proto3";
Название файла должно быть ocp_vacancy_api.proto
https://developers.google.com/protocol-buffers/docs/style?hl=ru

2021-08-18 15:29 UTC, bukhtiyarovanton commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +    uint64 ID = 1;
Переделаю, но Сергей "Сириус" на лекции говорил, что в Озоне PascalCase используется.

2021-08-18 15:34 UTC, bukhtiyarovanton commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +syntax = "proto3";
Тоже переделаю, но вдохновлялся этой репой https://github.com/ozoncp/ocp-task-api/tree/master/api/ocp-task-api, там протофайл с дефисами

2021-08-18 15:52 UTC, bukhtiyarovanton commented on Dockerfile
> +EXPOSE 8081 8082
исправил

2021-08-18 15:52 UTC, bukhtiyarovanton commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +    uint64 ID = 1;
исправил

2021-08-18 15:59 UTC, bukhtiyarovanton commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +syntax = "proto3";
исправил

2021-08-19 08:00 UTC, ivanmakarychev commented on api/ocp-vacancy-api/ocp-vacancy-api.proto
> +    uint64 ID = 1;
в нашей команде мы стараемся придерживаться snake_case

2021-08-19 08:01 UTC, ivanmakarychev approved these changes

2021-08-19 09:13 UTC, merged